-- MySQL Script generated by MySQL Workbench
-- Thu Nov  1 14:01:34 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `tecnico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecnico` (
  `tecnico_id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`tecnico_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente` (
  `cliente_id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `contacto` BIGINT(14) NOT NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `endereco` TEXT(400) NULL,
  `nif` BIGINT(30) NULL,
  PRIMARY KEY (`cliente_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assistencia` (
  `assistencia_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `tecnico_id` LONGTEXT NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `cor` VARCHAR(45) NULL,
  `serial` VARCHAR(45) NULL,
  `problema` TEXT(2000) NOT NULL,
  `orcamento` BIGINT(8) NULL,
  `relatorio_interno` TEXT(10000) NULL,
  `relatorio_cliente` TEXT(1000) NULL,
  `material` LONGTEXT NULL,
  `preco` VARCHAR(8) NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`assistencia_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artigo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artigo` (
  `artigo_id` INT NOT NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `localizacao` VARCHAR(5) NULL,
  `qty` INT NULL,
  PRIMARY KEY (`artigo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `encomenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `encomenda` (
  `encomenda_id` INT NOT NULL,
  `artigo_id` INT NOT NULL,
  `assistencia_id` INT NULL,
  `cliente_id` INT NULL,
  `observacao` TEXT(1000) NULL,
  `estado` VARCHAR(45) NOT NULL,
  `previsao_entrega` DATE NOT NULL,
  `orcamento` INT NULL,
  `fornecedor` VARCHAR(200) NULL,
  `qty` INT NULL,
  PRIMARY KEY (`encomenda_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
